### ISSUE TITLE
Error occurred when uploading turtlebot3_with_openmanipulator_core.

### ISSUE THREAD

**Issue by Kanelankai** [ROBOTIS-GIT/OpenCR#109]
Sorry for disturbing you.
Thank you for helping me solve the former problem.
Now I want to use openmanipulator with turtlebot3.
I tried to upload turtlebot3_with_openmanipulator_core to opencr following this link.
http://emanual.robotis.com/docs/en/platform/turtlebot3/manipulation/#opencr-setup
However, an error occurred when compiling the code, showing 
'class Turtlebot3Sensor ' has no member named 'getPushedBumper'.
The opencr firmware version is 1.2.0.
Should I comment out the line concerning "getPushedBumper" before uploading to openCR manually?
In fact, the former problem occurred when I tried to uploaded the code after comment out this line.

Another question is that if "turtlebot3_with_openmanipulator_core" is successfully uploaded to openCR. "turtlebot3_core" is overwritten. So can the motors of wheels run as normal?

Thank you in advance!

**Comment by OpusK** [comment]
For about error in turtlebot3_with_openmanipulator_core.ino, please refer to [this link](https://github.com/ROBOTIS-GIT/turtlebot3/issues/240)

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
