### ISSUE TITLE
error: cannot convert 'USBSerial*' to 'HardwareSerial*' in assignment

### ISSUE THREAD

**Issue by wsung1** [ROBOTIS-GIT/OpenCR#120]
Hi, ROBOTIS,
While following the textbook - ROS robot programming written by @robotpilot, I got stuck in 9.2.6. rosserial (p.274) with the following error

Arduino: 1.8.5 (Linux), Board: "OpenCR Board, OpenCR Bootloader"

In file included from /home/futuremobilitylab01/Arduino/libraries/ros_lib/ros.h:43:0,
                 from /home/futuremobilitylab01/.arduino15/packages/OpenCR/hardware/OpenCR/1.3.1/libraries/ROS/examples/01. Basics/a_LED/a_LED.ino:19:
/home/futuremobilitylab01/Arduino/libraries/ros_lib/ArduinoHardware.h: In constructor 'ArduinoHardware::ArduinoHardware()':
/home/futuremobilitylab01/Arduino/libraries/ros_lib/ArduinoHardware.h:79:16: error: cannot convert 'USBSerial*' to 'HardwareSerial*' in assignment
       iostream = &Serial;
                ^
Multiple libraries were found for "ros.h"
 Used: /home/futuremobilitylab01/Arduino/libraries/ros_lib
 Not used: /home/futuremobilitylab01/.arduino15/packages/OpenCR/hardware/OpenCR/1.3.1/libraries/turtlebot3_ros_lib
exit status 1
Error compiling for board OpenCR Board.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

The error actually resulted from Arduino IDE \ File \ Examples \ ROS \ 01.Basics \ a_LED but other examples in this category fell under the same problem.
The similar problem has been reported as follows but to my regret I couldn't get the hang of its solution yet.
https://groups.google.com/forum/#!topic/korea-ros-users/NRbZ5nee8e0
https://answers.ros.org/question/272411/opencr-software-setup/
https://m.blog.naver.com/PostView.nhn?blogId=chandong83&logNo=221009668897&proxyReferer=https%3A%2F%2Fwww.google.com%2F
Please help!

**Comment by OpusK** [comment]
Hi, @wsung1 

Please refer to 58~59line and 64, 76line in [this code.](https://github.com/ROBOTIS-GIT/OpenCR/blob/master/arduino/opencr_arduino/opencr/libraries/turtlebot3_ros_lib/ArduinoHardware.h)

This error is due to type mismatch between SERIAL_CLASS and the actual hardware class.

**Comment by wsung1** [comment]
@OpusK, thanks to your support, the error was solved :)

**Comment by Omkar-Jadhav** [comment]
Hello @wsung1 @OpusK Can you please explain how to solve the error and what exactly do we need to look and change in the referred code?

**Comment by ROBOTIS-Will** [comment]
@Omkar-Jadhav 
Since you didn't share the terminal output, I'm not sure what cause the problem, but assuming that you are having an identical issue with the above posting, you might have a conflicting ros library under your /home/$USER/Arduino/libraries/ directory.
When building OpenCR ROS example, you don't need other libraries as OpenCR board package has all necessary libraries in it.
The easiest resolution will be removing the conflict library from your `/home/$USER/Arduino/libraries/`
