### ISSUE TITLE
error: Connection refused

### ISSUE THREAD

**Issue by wsung1** [ROBOTIS-GIT/OpenCR#123]
Hi, ROBOTIS,
While following the textbook - ROS robot programming, I got stuck in 9.2.6. rosserial examples (p.276). As written in the textbook, I first downloaded a_LED.ino to the OpenCR.
![download a_led ino](https://user-images.githubusercontent.com/26803880/44513235-cb22f980-a6f7-11e8-89ff-d476d0d3828b.png)

Then, I tried to run rosserial_server using rosserial_python as shown below but it failed with the following error:
![socket error](https://user-images.githubusercontent.com/26803880/44513248-cf4f1700-a6f7-11e8-87e6-332eb170c9de.png)

Please help me solve this problem.
Thanks in advance :)

**Comment by kijongGil** [comment]
Hi wsung1 :)
I think ros is installed incorrectly, or the python configuration seems to be wrong.
could you try to install ros-serial?
`sudo apt-get install ros-kinetic-rosserial ros-kinetic-rosserial-server ros-kinetic-rosserial-arduino
`

**Comment by wsung1** [comment]
Thanks for your reply @kijongGil :) 
The cause was turned out to be activating ROS_MASTER_URI.
https://answers.ros.org/question/248280/rosserial-arduino-connectivity-problem-socketerror-errno-111-connection-refused/
