### ISSUE TITLE
Searching for API document

### ISSUE THREAD

**Issue by wsung1** [ROBOTIS-GIT/OpenCR#124]
Hi, @OpusK :)
I'm walking through the CAN examples you made such as canTxRxMessage.
It says /* For API doc, please refer to https://github.com/ROBOTIS-GIT/OpenCR/wiki/arduino_examples_can */ but nothing could be found via this link.
Where can I obtain the API document?
Thank you, @OpusK!

**Comment by wsung1** [comment]
Thanks for replying @OpusK.
So, is there no way to approach the API document right away?

**Comment by OpusK** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.

**Comment by amburkoff** [comment]
please do emanual and usage examples

**Comment by OpusK** [comment]
@amburkoff 

[APIs and example of CAN have been updated today](https://github.com/ROBOTIS-GIT/OpenCR/commit/11bba7a3c5a526664a9eb679b2fb25a2d66ac1c8). 
These are currently in develop branch, and we will add it to emanual when it is officially released.
