### ISSUE TITLE
CAN port in OpenCR

### ISSUE THREAD

**Issue by wsung1** [ROBOTIS-GIT/OpenCR#125]
Hi, ROBOTIS,
Among several communication ports that serve in OpenCR, only CAN has no information except its connector is 20010WS-04 (4-pin male connector).
http://emanual.robotis.com/docs/en/parts/controller/opencr10/
I'm also wondering why there are 4 pins for the one single CAN channel.
Please let me know at least the pin map for this in that which one is CAN high/low and so on.
Thanks in advance!

**Comment by OpusK** [comment]
Hi, @wsung1 ,

Sorry for late reply you.
Please refer to the figure below. (This is also shown on the OpenCR board)
![opencr_product](https://user-images.githubusercontent.com/18085958/45581425-9bbb7300-b8d8-11e8-8eec-951247533029.png)

The CAN pin map will be updated later in e-manual.

**Comment by wsung1** [comment]
Thanks for replying @OpusK, but I'm still wondering what G and V pins do.
As far as I know, CAN generally consistas of H and L.

**Comment by OpusK** [comment]
As you say, CAN can communicate using High / Low only.
It seems to have been added at the hardware design stage because it may require G / V depending on the user.

**Comment by KurtE** [comment]
@wsung1, obviously someone from Robotis can answer this better than I can... 

But for issues like, this, I usually find it helps to look at the schematic and other design files. 
You can find the Schematic through the E-Manual or directly from github: https://github.com/ROBOTIS-GIT/OpenCR-Hardware/blob/master/Schematic/OpenCR_REVF_Schematic.pdf

So if you look at Sheet 8 at the CAN section you will see that:
G - Ground
V - Is voltage of what looks like 5 Volts.

So these two pins allow you to apply power and ground, which may be needed by a Can device.  Note: You almost always require a ground...

**Comment by wsung1** [comment]
@KurtE, I'd appreciate for your pieces of advice. It helps me a lot! :)

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.

**Comment by kaif-46** [comment]
@OpusK @KurtE @wsung1 Will, you be able to provide some information about how to access these pins in the code and how can we send/receive data over it?

**Comment by KurtE** [comment]
Sorry I have not played with OpenCR for a couple of years now... So not much help on this one. anymore.

**Comment by ROBOTIS-Will** [comment]
@kaif-46 

Please create a new issue thread since this thread had been closed long ago.

You may refer to the CAN example provided in the OpenCR Arduino board manager.
![image](https://user-images.githubusercontent.com/26239359/149699081-fa8ebaa7-2c05-4e36-8421-b1b6970d167d.png)

Please checkout our eManual to find out how to install the required library for OpenCR.
https://emanual.robotis.com/docs/en/parts/controller/opencr10/#arduino-ide

Thanks!

**Comment by kaif-46** [comment]
How can i change the frequency to 8MHz for CAN communication.

**Comment by ROBOTIS-Will** [comment]
Please refer to the thread #296.
