### ISSUE TITLE
Compile error - fatal error: stddef.h: No such file or directory

### ISSUE THREAD

**Issue by wsung1** [ROBOTIS-GIT/OpenCR#127]
Hi, ROBOTIS,
Have you ever encountered the error as shown below when you compile the firmware for use in TB3 burger using arduino IDE?

Arduino: 1.8.5 (Linux), Board: "OpenCR Board, OpenCR Bootloader"

In file included from /home/cutop11/.arduino15/packages/OpenCR/hardware/OpenCR/1.3.1/cores/arduino/Arduino.h:24:0,
                 from sketch/turtlebot3_core.ino.cpp:1:
/home/cutop11/.arduino15/packages/OpenCR/tools/opencr_gcc/5.4.0-2016q2/arm-none-eabi/include/stdlib.h:16:20: fatal error: stddef.h: No such file or directory
compilation terminated.
exit status 1
Error compiling for board OpenCR Board.

Note that this error is not derived from arduino IDE itself but from somewhere else in my local computer.
Thank you for your interest!

**Comment by kijongGil** [comment]
Hi @wsung1 :)
I'm sorry for late reply.
Could you tell me  when you get this error?

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
