### ISSUE TITLE
Power breaker circuit of openCR

### ISSUE THREAD

**Issue by XiafeiWang** [ROBOTIS-GIT/OpenCR#134]
Hi,
I am new of openCR. The output power is short circuit because of my misoperation, thus leading to the breaker circuit of power supply. Is there a overload protection switch on the board or any other methods to solve this question? Thank you

**Comment by OpusK** [comment]
Hi, @XiafeiWang 

Can I see pictures of your product?
There is a fuse for power protection. 
![20181004_135029_hdr](https://user-images.githubusercontent.com/18085958/46453536-f57ad300-c7dc-11e8-9808-2a6ffd03bef7.jpg)

Please check the status of fuse on the back of OpenCR.

**Comment by XiafeiWang** [comment]
> Hi, @XiafeiWang
> 
> Can I see pictures of your product?
> There is a fuse for power protection.
> ![20181004_135029_hdr](https://user-images.githubusercontent.com/18085958/46453536-f57ad300-c7dc-11e8-9808-2a6ffd03bef7.jpg)
> 
> Please check the status of fuse on the back of OpenCR.

Yes, this's it. I have replaced a new one. Thank you!
