### ISSUE TITLE
My battery of turtlebot3 is brocken. Can I power supply the OpenCR with the 12V adapter? If not how can I use it without a battery?

### ISSUE THREAD

**Issue by stevensu1838** [ROBOTIS-GIT/OpenCR#144]

**Comment by OpusK** [comment]
Yes, it is possible.
Please refer to [e-manual](http://emanual.robotis.com/docs/en/parts/controller/opencr10/#specifications).

**Comment by gpwhd07** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
