### ISSUE TITLE
udev rule clarification

### ISSUE THREAD

**Issue by LucidOne** [ROBOTIS-GIT/OpenCR#168]
Can someone please confirm that this udev rule is for the RPLidar on the TB3?
```
ATTRS{idVendor}=="10c4" ATTRS{idProduct}=="ea60", ENV{ID_MM_DEVICE_IGNORE}="1", MODE:="0666"
```

Thanks!

**Comment by OpusK** [comment]
Yes, that's right!

 - [TB3 rules](https://raw.githubusercontent.com/ROBOTIS-GIT/turtlebot3/master/turtlebot3_bringup/99-turtlebot3-cdc.rules)
    - First: ST Micro Virtual COM
    - Second: DFU
    - Third: OpenCM9.04
    - Forth: RPLidar on TB3
