### ISSUE TITLE
uploading firmware with opencr_ld

### ISSUE THREAD

**Issue by wecracy** [ROBOTIS-GIT/OpenCR#172]
Hi.
I want to upload from raspberryPi, which connected with OpenCr board through USB port, using opencr_ld. But I can't upload my pre-build firmware, with syntax error ("(" unexpected).

Log:
 $ sudo ./opencr_ld /dev/ttyACM0 115200 ./d_IMU.ino.OpenCR.bin 1
./opencr_ld: 1: ./opencr_ld: Syntax error: "(" unexpected

Also when I use the 'update.sh' instead of opencr_ld, it recognize my firmware as no opencr firmware.

Log:
$ sudo ./update.sh /dev/ttyACM0 ../binary/d_IMU.ino.OpenCR.bin 
armv7l
arm
OpenCR Update Start..
opencr_ld_shell ver 1.0.0
opencr_ld_main 
[  ] file name   	: ../binary/d_IMU.ino.OpenCR.bin 
[  ] file size   	: 127 KB
[NG] not opencr fw 
[  ] file name   	: ../binary/d_IMU.ino.OpenCR.bin 
[  ] file size   	: 127 KB
[NG] not opencr fw 
[  ] file name   	: ../binary/d_IMU.ino.OpenCR.bin 
[  ] file size   	: 127 KB
[NG] not opencr fw

I built firmware by 'Export compiled Binary.' In the configuration, board is set as 'OpenCRBoard' and upload method is set as 'OpenCRBootloader.'
Is there something wrong?

**Comment by OpusK** [comment]
Hi, @wecracy 

> $ sudo ./opencr_ld /dev/ttyACM0 115200 ./d_IMU.ino.OpenCR.bin 1
./opencr_ld: 1: ./opencr_ld: Syntax error: "(" unexpected

Please refer to the following link for the above contents.
 - [shell-script-fails-syntax-error-unexpected](https://unix.stackexchange.com/questions/45781/shell-script-fails-syntax-error-unexpected)
Do not use the `sudo` keyword or use the `sudo bash` command.


>$ sudo ./update.sh /dev/ttyACM0 ../binary/d_IMU.ino.OpenCR.bin
armv7l
arm
OpenCR Update Start..
opencr_ld_shell ver 1.0.0
opencr_ld_main
[ ] file name : ../binary/d_IMU.ino.OpenCR.bin
[ ] file size : 127 KB
[NG] not opencr fw

As you can see from the error message `not opencr fw`, the binary file you are using is not the binary required by opencr_ld_shell.
In OpenCR, you need to process the binaries one more time and upload them. (Please use the opencr_ld_shell make command)

**Comment by wecracy** [comment]
Thanks!
