### ISSUE TITLE
Cannot operate dynamixels

### ISSUE THREAD

**Issue by unverciftci** [ROBOTIS-GIT/OpenCR#173]
Hi,
OpenCR's led example is working but I cannot operate dynamixels. ID's are correct. I receive no errors but Dynamixel XL4230 doesn't respond.

**Comment by OpusK** [comment]
> OpenCR's led example is working but I cannot operate dynamixels. ID's are correct. I receive no errors but Dynamixel XL4230 doesn't respond.

Hi, @unverciftci 

What is the example you used? Since OpenCR has the DYNAMIXEL Power Enable pin, you must activate it. Have you tested with examples related to DYNAMIXEL? If so, which example did you test?

**Comment by unverciftci** [comment]
I tried the position example with power enabled but it doesn't work.

**Comment by OpusK** [comment]
Hi, @unverciftci 

Please try to control it from PC through [usb_to_dxl example](https://github.com/ROBOTIS-GIT/OpenCR/blob/master/arduino/opencr_arduino/opencr/libraries/OpenCR/examples/10.%20Etc/usb_to_dxl/usb_to_dxl.ino).

As a precaution, make the [`DXL_BAUD 'value on line 10](https://github.com/ROBOTIS-GIT/OpenCR/blob/master/arduino/opencr_arduino/opencr/libraries/OpenCR/examples/10.%20Etc/usb_to_dxl/usb_to_dxl.ino#L10) equal to the speed of the actuator you want to use.

**Comment by mclaubee** [comment]
Hi, I was having the same problem. Everything is working except DXL port.

**Comment by OpusK** [comment]
Hi, @mclaubee 

What example are you using?
And, did you put the proper power for OpenCR?
If you have a multimeter, can you check if the voltage is normal?

And would you check if the switch in the picture below is on?


![image](https://user-images.githubusercontent.com/18085958/58520700-fb9e4380-81f3-11e9-83a6-48e50c9b0a6f.png)

**Comment by mclaubee** [comment]
​Hi Kai, 
Thanks for your prompt reply. Yes, I use a 12V power supply, from OP3. And yes I turn the switch on. 

I tried opencr_op3, it couldn't turn on the dynamixel's port power (24), returned an unknown error. 

Then I tried ping, model_scan, Find_Dynamixel, usb_to_dxl, etc from Arduino, but none of them is able to find the servos.

**Comment by benoit-girard** [comment]
I have a similar problem: using a turtlebot3, I followed the OpenCR setup instructions (http://emanual.robotis.com/docs/en/platform/turtlebot3/opencr_setup/#opencr-setup), I obtained the expected `jump_to_fw` output, however the "6.3.2 basic operation" test does not work.

The robot does not move after pressing SW1 or SW2, when it operates on the battery (switch on the OpenCR is on).

What could I do to identify the source of the problem?

**Comment by benoit-girard** [comment]
Problem solved, but I don't know why: I did again the setup using the raspberry & the shell setup, and now it works. Sorry for the inconvenience.

**Comment by OpusK** [comment]
Hi, @benoit-girard 

> I obtained the expected jump_to_fw output, however the "6.3.2 basic operation" test does not work.

This is related to #191 and has been fixed in the Master version.
Since Turtlebot3 core images are managed separately, we recommend using a possible script method.
We apologize for any inconvenience.

**Comment by OpusK** [comment]
@mclaubee 

Sorry. I was missing this issue.
Have you been resolved?

**Comment by OpusK** [comment]
This issue has been closed as there weren't recent activities. Please feel free to reopen this thread if there's any opinion to throw. Thanks.

**Comment by mclaubee** [comment]
Hi Kei,

No solution yet. I actually just bypassed the OpenCRand directly control the servos through U2D2, just missing the IMU and buttons. But I'm still interested to figure out what's the problem. I will be going to Changwon, Korea in August for FIRA. Will Robotis setting a booth at the venue?
