### ISSUE TITLE
Can't send a can_message_t with the length of 0.

### ISSUE THREAD

**Issue by Heisenberg515** [ROBOTIS-GIT/OpenCR#174]
Hello,
Recently, I want to use your library of CAN to send a message with the length of 0, which is a SYNC in CANopen. However, I can't do that, the message can't be sent.
I wonder if you could help me out.
Thanks.

**Comment by OpusK** [comment]
Hi, @Heisenberg515 

In the current OpenCR code, if the length is less than 0, no data is being transmitted.
I will update next week about this.

**Comment by OpusK** [comment]
I have updated this feature to [can_zerobyte_write branch.](https://github.com/ROBOTIS-GIT/OpenCR/tree/feature/can_zerobyte_write)

Would you like to test it?

**Comment by Heisenberg515** [comment]
Hi, @OpusK 
It really works! 👍 
Thx
