### ISSUE TITLE
Support for Adafruit Proximity Sensor

### ISSUE THREAD

**Issue by MacRichiee** [ROBOTIS-GIT/OpenCR#182]
Hi, I'm new to Arduino and OpenCR on a whole, and am trying to set up some proximity sensors (Adafruit APDS9960) but to no avail. I tried the code below on an Arduino Mega, but am lost as to why it is not working on the OpenCR board. Hope you can point me in the right direction!

I'm using Pin3 as the interrupt, with a 3.3V input and SDA/SCL pins.
[
[LED_Interrupt.txt](https://github.com/ROBOTIS-GIT/OpenCR/files/3265126/LED_Interrupt.txt)
](url)

**Comment by OpusK** [comment]
@MacRichiee 

Please check the [pinmap of OpenCR](http://emanual.robotis.com/docs/en/parts/controller/opencr10/#arduino-connector).

Unlike UNO or OpenCR, Mega has more pins, so you need to check it out.
If you are a beginner of Arduino, please refer to the example of Uno or Leonardo, not Mega, and apply it to OpenCR.

**Comment by OpusK** [comment]
This issue has been closed as there weren't recent activities. Please feel free to reopen this thread if there's any opinion to throw. Thanks.
