### ISSUE TITLE
BT410 garbage value

### ISSUE THREAD

**Issue by HwangHanGyeol** [ROBOTIS-GIT/OpenCR#187]
OpenCR and BT410 modules are used.
When the BT410 module is disconnected, the garbage value comes on.
How can we solve this?

**Comment by OpusK** [comment]
Hi, @HwangHanGyeol 

This is probably due to the nature of the BT410. If so, please ask the ROBOTIS homepage Forum.

However, first of all, please let me know what garbage values are coming up, and give us detailed information about the baud rate setting and the environment you have tested.

**Comment by OpusK** [comment]
This issue has been closed as there weren't recent activities. Please feel free to reopen this thread if there's any opinion to throw. Thanks.
