### ISSUE TITLE
Using Both Protocols in Code

### ISSUE THREAD

**Issue by lisasavage** [ROBOTIS-GIT/OpenCR#189]
Hello,

Somewhat related to the issue brought up [here](https://github.com/ROBOTIS-GIT/OpenCR/issues/181), we are looking to use an OP2 FSR with an OpenCR that is also controlling XM540s. Is there a way to either a) run both Protocol 1.0 and Protocol 2.0 at the same time or b) switch between the 2 so that running all hardware is possible? Or will we need to go the route proposed by the original poster of the linked issue and use a separate board?

Lisa

**Comment by OpusK** [comment]
Hi, @lisasavage 

> a) run both Protocol 1.0 and Protocol 2.0 at the same time 

It is impossible at the same time. This is not possible due to protocol and hardware limitations (see the DYNAMIXEL protocol document for this).

That is, they all have to use the same protocol, or change the protocol each time and access each device sequentially.

**Comment by OpusK** [comment]
This issue has been closed as there weren't recent activities. Please feel free to reopen this thread if there's any opinion to throw. Thanks.
