### ISSUE TITLE
Make turtlebot3 friend monster function with ROS?

### ISSUE THREAD

**Issue by CaoKha** [ROBOTIS-GIT/OpenCR#194]
Hi,
I want to upgrade my turtle bot to become a turtle bot friend (monster). However, the code from ROBOTIS is only work with 2 wheels left and right. Can you provide some supports how to make turtlebot friends monster (4 wheels) functioning with ROS?
I found that the code of turtlebot3_friend_monster written by ROBOTIS using Hardware_interruption with different "control period" comparing to turtlebot_waffle.
It's difficult to fix these code to work with ROS.
Do you have any ideas how to make this work ?
Thank you,

**Comment by rjshim** [comment]
@CaoKha 

We do not officially support any TB3 friends ROS packages. You will need to make one for TB3 monster on your own. Someone made his own packages for [TB3 mecanum](https://github.com/Seunghooon/turtlebot3_mecanum) so please refer to them if needed.

Regards,
Ryan
