### ISSUE TITLE
turtlebot3_core example in Arduino IDE not working but the shell script does work?

### ISSUE THREAD

**Issue by CaoKha** [ROBOTIS-GIT/OpenCR#195]
Hi,
I am using Arduino IDE 1.8.9 and trying to upload the code of turtlebot3_core to OpenCR.
However, the motor didn't move after uploading success. 
Later, I try the shell script uploading method and it works but I don't know why.
Can someone explain this issue ?
Thanks,

**Comment by OpusK** [comment]
Hi, @CaoKha 

The TB3 binary file was fine, but this problem occurred when one of the contributors modified the code.
This issue is currently fixed in OpenCR 1.4.9. Please try after the update.

**Comment by CaoKha** [comment]
Hi @OpusK,
Thanks for the update :)
