### ISSUE TITLE
Verry,Verry bad I Erase My OpenCR of Flash and My computer don`t find my OpenCR USB Device

### ISSUE THREAD

**Issue by 18784506782** [ROBOTIS-GIT/OpenCR#196]
Recently,I wan keil program build my project and download. at download program,I Erase OpenCR flash.NOW the OTG of stm32f746 chip connect my compute Nothing has changed。 use the command: lsusb  can`t find USB Equipment and I according to yours document do press boot next pess reset key 。I doubt  the issue reason is that the DFU function of STM32f746ZGT6 cause。please teach  me  a method to slove the issues.thank you for my best。

**Comment by OpusK** [comment]
Hi, @18784506782 

>  I according to yours document do press boot next pess reset key 

If you follow the instructions above, is the DFU driver caught?

**Comment by OpusK** [comment]
This issue has been closed as there weren't recent activities. Please feel free to reopen this thread if there's any opinion to throw. Thanks.
