### ISSUE TITLE
DynamixelWorkbench - The Maximum Dynamixel Control Frequency Is Limited by Delays

### ISSUE THREAD

**Issue by mamaheux** [ROBOTIS-GIT/OpenCR#197]
Hi,

I am using the `DynamixelWorkbench` class to control 7 Dynamixel servos and I am not able to control the servo positions at a frequency higher than 14 Hz because there are `delay` function calls in all `writeRegister` and `writeOnlyRegister` methods of the `DynamixelDriver` class.

I don't understand why there are those `delay` function calls. Is it possible to remove them?

Thank you

**Comment by rjshim** [comment]
@mamaheux 

Please leave Dynamixel-Workbench-related questions at the following [link](https://github.com/ROBOTIS-GIT/dynamixel-workbench/issues).

Thanks!
