### ISSUE TITLE
Spelling mistake in usage message

### ISSUE THREAD

**Issue by mkhuthir** [ROBOTIS-GIT/OpenCR#207]
Please correct line 64 in "**arduino/opencr_develop/opencr_ld_shell/main.c**"

from "fprintf( stderr, "       opencr_ld_**sheel** view fw_name\n" );"
to "fprintf( stderr, "       opencr_ld_**shell** view fw_name\n" );"

**Comment by KyoungHwan2046** [comment]
Hi, @mkhuthir 
I will update this issue on next release.

**Comment by mkhuthir** [comment]
Thanks
