### ISSUE TITLE
LED pins are not as per e-manual

### ISSUE THREAD

**Issue by mkhuthir** [ROBOTIS-GIT/OpenCR#214]
e-Manual stating that LED pins are:

![image](https://user-images.githubusercontent.com/3192974/66851242-6fff3680-ef8b-11e9-9abb-d34794b79b11.png)

Current firmware 1.2.3 is using:

Front_left = BDPIN_GPIO_6
Front_right = BDPIN_GPIO_8
Back_left   = BDPIN_GPIO_10
Back_right =BDPIN_GPIO_12

please check. Also I noticed in your video on how to connect LEDs to OpenCR, there are no resistors added 

![image](https://user-images.githubusercontent.com/3192974/66851938-f6684800-ef8c-11e9-9608-ec532146d708.png)

I think we need to add a resistor for each LED. See below link for info.
http://www.resistorguide.com/resistor-for-led/

**Comment by KyoungHwan2046** [comment]
Hi, @mkhuthir .

We just found out that the circuit of the video is wrong.

Your opinion is right. The resistor should be in the circuit.

We'll make correct the e-manual with uploading of correct circuit.

Thank you.

**Comment by mkhuthir** [comment]
hi @KyoungHwan2046 

thank you very much; what about pin numbers ?

**Comment by mkhuthir** [comment]
Thank you very much.

**Comment by KyoungHwan2046** [comment]
@mkhuthir 

I have a question.

You said that
> current firmware 1.2.3 is using:
> Front_left = BDPIN_GPIO_6
> Front_right = BDPIN_GPIO_8
> Back_left = BDPIN_GPIO_10
> Back_right =BDPIN_GPIO_12
but I cannot found where this code is. 
Would you tell me where did you find this code?

And the last edit of led pin configuring is can find here.
> https://github.com/ROBOTIS-GIT/OpenCR/commit/190d9501aaba443e0e2380734daa07b2cc6a1081#diff-fe87ed179ef2b783508b98b1fb99ecdbR388

**Comment by mkhuthir** [comment]
@KyoungHwan2046 

The pin numbers I mentioned are the actual active pins when I tested firmware 1.2.3 on my TurtleBot3 hardware. its not taken from code.

**Comment by KyoungHwan2046** [comment]
@mkhuthir 

Could you please upload a picture that you connect pins?

Well, The openCR-binary code is based on the "openCR" code and you can see the configuration of led pins on 

>https://github.com/ROBOTIS-GIT/OpenCR/blob/master/arduino/opencr_arduino/opencr/libraries/turtlebot3/src/turtlebot3/turtlebot3_sensor.cpp#L386
.

So, if the openCR with 'openCR-binary' code works different, than we will update on next release.

**Comment by mkhuthir** [comment]
Im using the firmware binary from the following link:

https://github.com/ROBOTIS-GIT/OpenCR-Binaries/tree/master/turtlebot3/ROS1/latest

I will upload the photos soon.

**Comment by mkhuthir** [comment]
Hello @KyoungHwan2046 

Sorry I could not share photos today because my TurtleBot3 not with me now. However I searched the code and I think I found the issue is in lines **62-79** of [chip.h](https://github.com/ROBOTIS-GIT/OpenCR/blob/113d56689d51fafc3b4547e5e77d2f3cf94b1621/arduino/opencr_arduino/opencr/variants/OpenCR/chip.h).

correct code should be:

```
#define BDPIN_GPIO_3            50
#define BDPIN_GPIO_4            51
#define BDPIN_GPIO_5            52
#define BDPIN_GPIO_6            53
#define BDPIN_GPIO_7            54
#define BDPIN_GPIO_8            55
#define BDPIN_GPIO_9            56
#define BDPIN_GPIO_10           57
#define BDPIN_GPIO_11           58
#define BDPIN_GPIO_12           59
#define BDPIN_GPIO_13           60
#define BDPIN_GPIO_14           61
#define BDPIN_GPIO_15           62
#define BDPIN_GPIO_16           63
#define BDPIN_GPIO_17           64
#define BDPIN_GPIO_18           65
#define BDPIN_GPIO_19           66
#define BDPIN_GPIO_20           67
```

![image](https://user-images.githubusercontent.com/3192974/66941451-f1bc9600-f057-11e9-89a2-850fc91749c1.png)

**Comment by mkhuthir** [comment]
@KyoungHwan2046 

Below are connection photos for your info. this is the correct connection after clearing confusion.
![image](https://user-images.githubusercontent.com/3192974/67137949-d1562c80-f24d-11e9-915d-cc3b68056e42.png)
![image](https://user-images.githubusercontent.com/3192974/67137958-f185eb80-f24d-11e9-9d10-75de5b7d202f.png)
![image](https://user-images.githubusercontent.com/3192974/67137966-08c4d900-f24e-11e9-8ada-d2cb28cad1a5.png)

**Comment by KyoungHwan2046** [comment]
Hi, @mkhuthir .

Thank you for your update. 

The pin map of the video is wrong and the modified video will be updated soon.

Once again, thank you for your help and supports.

**Comment by mkhuthir** [comment]
Thank you very much @KyoungHwan2046

**Comment by KyoungHwan2046** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
