### ISSUE TITLE
install opencr package via board manager

### ISSUE THREAD

**Issue by techjjun** [ROBOTIS-GIT/OpenCR#220]
I'm using Nvidia XAVIER board as SBC (ubuntu 18.04 LTS) and following emanual.robotic to install opencr package

in arduino IDE.  but it looks like unmet operating system and wanna know what it is..

![Screenshot from 2019-11-08 22-53-37](https://user-images.githubusercontent.com/37102770/68481481-ab371180-027a-11ea-85bb-05ecea38e838.png)

**Comment by KyoungHwan2046** [comment]
Hi @techjjun 

I'm sorry for the late reply.

We will checking the installation with board manager on the arm platform.

**Comment by techjjun** [comment]
Thanks for the reply, I'll keep waiting for the respond.

**Comment by KyoungHwan2046** [comment]
Hi @techjjun 

I'm sorry for the late reply.

We do not support the installation on the arm platform like XAVIER or raspberry pi. 

So, please use PC or laptop to use openCR.

**Comment by robotiscustomer** [comment]
Hi, I am confused about the advice given above. We know that in the Turtlebot 3, raspberry pi is used with OpenCR. Why it was mentioned that it is not supported?  I recall seeing the idea that OpenCR only supports Intel PC somewhere else. Under what situation is it true?

**Comment by ROBOTIS-Will** [comment]
@robotiscustomer 
The OpenCR package does not support ARM processor, which means you cannot build your source code using Arduino IDE on ARM based SBC such as RPi or Xavier. However, you can still download the compiled binary file using [OpenCR downloader](http://emanual.robotis.com/docs/en/parts/controller/opencr10/#downloader).

**Comment by robotiscustomer** [comment]
Thanks Will.
