### ISSUE TITLE
OpenCR library for ARM processor

### ISSUE THREAD

**Issue by Billwaa** [ROBOTIS-GIT/OpenCR#222]
Hi, 

I am following the eManual for installing the library for Arduino. I am doing this on a Raspberry Pi, since I am VNC-ing into the TurtleBot 3 Pi and want to program the OpenCR from there. But on the Arduino board manager, it said that opencr_gcc is not available for my OS. I am running Raspian Buster. Can someone point in the direction to get this install?

Thanks!

**Comment by ROBOTIS-Will** [comment]
@Billwaa 
Please see this issue posting #220 
Thank you.
