### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by vanem** [ROBOTIS-GIT/OpenCR#223]
The OpenCR board has a JTAG connector. However I have found no info how to use it. How could I use ST link to debug for example?

**Comment by KyoungHwan2046** [comment]
Hi @vanem 

We are not support the using of jtag with arduino IDE yet. 

You can use jtag with openCR code and another IDE, like a Truestudio, IAR, KEIL, or something else.

Thank you.

**Comment by KyoungHwan2046** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.

**Comment by Omar-Ismail** [comment]
Is it possible to know which type of connection could be made to the JTAG/SWD connector? The normal jumper wire that comes with any ST-Link V2 does not fit.

![image](https://user-images.githubusercontent.com/30232718/195450098-177e8664-f230-4b3a-ae22-5bbd9f69a07f.png)

**Comment by dtscbs** [comment]
This question was asked and answered several years ago.  Is JTAG support still not supported?
