### ISSUE TITLE
which libraries should i use for compile?

### ISSUE THREAD

**Issue by VanguardDream** [ROBOTIS-GIT/OpenCR#224]
i am doing project for my our robot using openCR.

there are two libraries that i have now.
One is that arduino board manager made. and other one is made by running rosserial script. (rosserial_arduino)
because i made some new ros message to use it in my project.

in my situation, which libraries should i use?

thank you.

**Comment by KyoungHwan2046** [comment]
Hi, @VanguardDream 

It doesn't matter what library you use, if it does works well.

Thank you.

**Comment by VanguardDream** [comment]
thank you. @KyoungHwan2046
