### ISSUE TITLE
Change distance between wheels and casters

### ISSUE THREAD

**Issue by zentala** [ROBOTIS-GIT/OpenCR#232]
I have TB3 Waffle Pi and I would like to increase a space between wheels and casters (make the robot base bigger and more stable). I will not change the size of the wheels. 

I found that I have to edit the `tb3_desc` package on the ROS side, but I also may need to do some reconfiguration on OpenCR side. 

0. Is there any manual on how to do it? I couldn't find any.
1. What should I change? `WHEEL_SEPARATION` and `TURNING_RADIUS`? What is `ROBOT_RADIUS`? I guess I need to change it but how?
2. Do all required changes should be done in file `turtlebot3_waffle.h` or there are any other files that I should modify?
3. Is it possible to do it with ROS2 or do I need to use ROS to edit the source code? (I don't see any configuration for ROS2 version)
4. Are there any additional steps (than flashing customize code via Arduino IDE) that I need to follow?
5. If my (custom) enclosure that will be built on top of waffles will be bigger then waffles itself (10cm outside from wheels) do I need to consider it in those settings (maybe in `ROBOT_RADIUS`)?

**Comment by ROBOTIS-Will** [comment]
@zentala 
Hi, we do not provide detail instructions on modifying the platform, but please refer to #225.
Once you change the OpenCR firmware from Arduino IDE, either upload the sketch from PC or use [OpenCR downloader](http://emanual.robotis.com/docs/en/parts/controller/opencr10/#downloader) when uploading binary file from RPi.
I also recommend to look for information from [ROS Answers](https://answers.ros.org/questions/).
Thank you.
