### ISSUE TITLE
Do we need to set the USB Latency Timer Setting when using the OpenCR under Linux?

### ISSUE THREAD

**Issue by robotiscustomer** [ROBOTIS-GIT/OpenCR#234]
Hi, under Section 5.4.1.2 USB Latency Timer Setting of the OpenManipulator-X e-Manual, it is mentioned that to set the latency time from 16ms to 1ms when using the U2D2, one should use:

$rscore
$rsrun open_manipulator_controller create_udev_rules

How about when using the OpenCR in different platforms such as the OpenManipulator-X, TurtleBot3, OP3 and user created robots that use OpenCR in ROS or Embedded environments? There is no mention about setting the latency to 1ms under Section 5.4.2 OpenCR.

Thanks

**Comment by ROBOTIS-Will** [comment]
@robotiscustomer 
You don't need to (and can't) set a latency timer for ttyACMx.
In case of ttyUSB with FTDI chips, default latency of 16ms is introduced and sometimes it prevents high speed communication between the host and peripheral devices.
