### ISSUE TITLE
TurtleBot3: BatteryState message needs to be updated for Noetic

### ISSUE THREAD

**Issue by theseankelly** [ROBOTIS-GIT/OpenCR#240]
The BatteryState message has some new fields in Noetic, see [this change](https://github.com/ros/common_msgs/commit/4804aa31c4df20c2143c7a09627a09039dafc1e0).

**Comment by ROBOTIS-Will** [comment]
@theseankelly Thank you for the ping :) We'll review this change and update the code.

**Comment by ROBOTIS-Will** [comment]
For the Noetic developers, please use `noetic-devel` branch in order to get a correct battery state message(#241). Thank you.
