### ISSUE TITLE
make opencr board by myself

### ISSUE THREAD

**Issue by woshidag** [ROBOTIS-GIT/OpenCR#25]
hi,i am making a opencr board(v2.0version),but there are some problems,could you take a hd photo of opencr board to help me.
my email:woshidag@yeah.net

**Comment by ROBOTIS-Leon** [comment]
Hey, how are you?

The photo you said is already uploaded on to the [ROSCon2016 presentation document](http://roscon.ros.org/2016/presentations/ROSCon2016_Turtlebot3_ROBOTIS.pdf)

**Comment by woshidag** [comment]
thanks
