### ISSUE TITLE
DXL Power

### ISSUE THREAD

**Issue by dabenpb** [ROBOTIS-GIT/OpenCR#251]
I posted this in OpenCR HW but got no repsonse:

I would have suspected that the DXL power would be regulated to 12V but it appears to be whatever is on the SMPS. Is that what you intend?

**Comment by ROBOTIS-Will** [comment]
Hi @dabenpb ,
Please refer to #249 as it is similar inquiry regarding the power.
Thanks.

**Comment by dabenpb** [comment]
Thank you.  I see the logic.
