### ISSUE TITLE
Ethernet

### ISSUE THREAD

**Issue by dabenpb** [ROBOTIS-GIT/OpenCR#252]
I see that the ARM supports the 10/100 Ethernet MAC with dedicated DMA:
supports IEEE 1588v2 hardware, MII/RMII.  Is there any example on how to modify to add the PHY?  I am currently using an Arduino Ethernet shield .

**Comment by ROBOTIS-Will** [comment]
Hi @dabenpb ,
Thank you for your inquiry, but we do not have an example for implementing PHY on OpenCR.

**Comment by ROBOTIS-Will** [comment]
This issue will be closed as there isn't recent activity. Please feel free to reopen when necessary.
