### ISSUE TITLE
OpenCR Setup - waffle Arduino code - NOETIC - battery_state_msg compile error

### ISSUE THREAD

**Issue by MikeHallettUK** [ROBOTIS-GIT/OpenCR#264]
@ OpenCR Setup for NOETIC: a suggestion:

1) if upgrading from Melodic: suggest let user know you need to upgrade to NOETIC Arduino library to 1.4.16

2) in waffle folder: Arduino code would not compile: 

_needs same as in burger folder_ = turtlebot3_core_config.h 

**Ln 167 =** 
// Battey state of Turtlebot3
#if defined NOETIC_SUPPORT
sensor_msgs::BatteryStateNoetic battery_state_msg;
#else
sensor_msgs::BatteryState battery_state_msg;
#endif

**Comment by ROBOTIS-Will** [comment]
Hi @MikeHallettUK 
Sorry about the delayed response on this issue.
I've transferred your ticket to a relative repository.
This has been fixed in the latest OpenCR board manager #261 
Thank you.
