### ISSUE TITLE
USB to DXL + Sensor Values ?!

### ISSUE THREAD

**Issue by Vinz1911** [ROBOTIS-GIT/OpenCR#266]
Hi Guys,

I want to control my Turtlebot Dynamixel Servos by Using the DynamixelSDK. So I uploaded the usb_to_dxl Library to the OpenCR and this is working very well. But is there a way to also read out the Sensor Values from the MPU9250 over USB ?

The usb_to_dxl needs the UART USB and its not possible to open a serial Port Twice. Is there a way to control my Dynamixels and also read out the sensor values from the board over the usb cable ?!

**Comment by ROBOTIS-Will** [comment]
Hi @Vinz1911 
A less painful way to do this is using the [Indirect Data](https://emanual.robotis.com/docs/en/dxl/x/xl430-w250/#indirect-address-indirect-data) of DYNAMIXEL.
When Indirect Address for the Indirect Data is not specified, the Indirect Data address can be used to store 1 byte value.
So I think implementing IMU update function in the loop() of usb_to_dxl sketch, and reading the Indirect Data addresses with DYNAMIXEL SDK will allow you to get the IMU value.
