### ISSUE TITLE
OpenCR binaries source code

### ISSUE THREAD

**Issue by joaoramosipl** [ROBOTIS-GIT/OpenCR#288]
Hello,
Is it possible to release the source code for the latest binary version of OpenCR for Waffle Pi?
I'm trying to manually flash it from Arduino IDE, but it fails during the bringup. If I flash the latest OpenCR binary, it works well. I need this to prepare the OpenManipulator-X integration, while the official examples aren't released.

Thanks for your attention.

**Comment by eslamsalahelsheikh** [comment]
I think you can find the OpenCR source code here https://github.com/ROBOTIS-GIT/OpenCR/tree/master/arduino/opencr_arduino/opencr/libraries. note that you need the dynamixel2arduino library version 0.3.0 to work.

**Comment by joaoramosipl** [comment]
Thank you for the fix. I'm seeing another problem that I stated on another issue.
