### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by yxldd** [ROBOTIS-GIT/OpenCR#293]
When  I  tried to add OpenCR manager on arduino IDE(on windows),  it always tell me that 
"Error downloading https://raw.githubusercontent.com/ROBOTIS-GIT/OpenCR/master/arduino/opencr_release/package_opencr_index.json"

**Comment by ROBOTIS-Will** [comment]
Hi @yxldd 
Please check if you can access the GitHub in your region.
Try opening the json file location on your web browser and see if you can read the content.
https://raw.githubusercontent.com/ROBOTIS-GIT/OpenCR/master/arduino/opencr_release/package_opencr_index.json
Thanks.

**Comment by yxldd** [comment]
> Hi @yxldd Please check if you can access the GitHub in your region. Try opening the json file location on your web browser and see if you can read the content. https://raw.githubusercontent.com/ROBOTIS-GIT/OpenCR/master/arduino/opencr_release/package_opencr_index.json Thanks.

Thanks for reply. I can access GitHub in my region, and post this issue successfully. And I can also see the content about the .json in my web browser.

**Comment by yxldd** [comment]
![image](https://user-images.githubusercontent.com/49592434/150087744-2b31e2dd-de23-4cf3-a82e-de881e6a3f68.png)
when I click the tools->Boards Manager, the arduino IDE will tell me this.
I am a new university student ,and maybe dont have enough ability to solve it.
THANKS FOR HELPING.
