### ISSUE TITLE
About default battery for OPENCR

### ISSUE THREAD

**Issue by minhlang102** [ROBOTIS-GIT/OpenCR#338]
Hi guys,

I've read on manual that it said default battery is LI-PO 11.1V 1,800mAh 19.98Wh. I had a question that could i use 3s Lipo battery, 6200mah 100c for OpenCR via T-plug?

Thanks in advance,

**Comment by shiba-8ro** [comment]
Hi @minhlang102 

OpenCR1.0 has a fuse.
I haven't tried high current LIPO, but you need to input power within the range that this fuse can safely use.
https://emanual.robotis.com/docs/en/parts/controller/opencr10/
![image](https://github.com/ROBOTIS-GIT/OpenCR/assets/5852451/833fc7f4-46c6-4aa8-9756-37429a6fb592)

**Comment by minhlang102** [comment]
Hello @shiba-8ro 

Thank you for your response.
I'm using Turtlebot3 and it doesn't draw current more than 10A. So is it safety if i use battery mentioned above?

**Comment by shiba-8ro** [comment]
@minhlang102 
I have never run a current of more than 5A through TB3, so I cannot guarantee it, but I think it is possible.
However, if you do so, please do so at your own risk.

**Comment by langung102** [comment]
Thank you, @shiba-8ro
i'll consider it.

**Comment by minhlang102** [comment]
Thank you, @shiba-8ro 
I'll consider it.
