### ISSUE TITLE
Issues with finding dynamixel on OpenCR 1.0

### ISSUE THREAD

**Issue by hozhu** [ROBOTIS-GIT/OpenCR#51]
Dear Robotis Representative,

My team recently purchased a turtlebot3 from robotis and the package came with a intel joule 570x board and OpenCR 1.0 board. We were trying to control one DYNAMIXEL XM430-W210-R by using the intel joule 570x board and the OpenCR 1.0 board. The program that we used was the simplest Dynamixel tutorial from the following website (http://wiki.ros.org/dynamixel_workbench_single_manager/Tutorials/CommandLine). By following the instruction, we were able to complete step 1, step 2 and step 3 without any issues. However, when we were executing a command line from step 4 (**roslaunch my_dynamixel_workbench_tutorial single_manager.launch**) ,  we received the following error: **Please Check USB Port authorization and Baudrate [ex: 57600,115200, 1000000, 3000000] ...Failed to find dynamixel!**. We have double checked the baudrate and model ID and they seemed to be correct.  We can't figure out why it is failing to find dynamixel. To make things clearer, we are attaching an image the entire process. Thank you for your help and time in advance! 

SIncerely,

Hong
![img-5526](https://user-images.githubusercontent.com/14323837/32589079-59bff238-c4c7-11e7-9bbb-087e39f70b8f.JPG)

**Comment by ROBOTIS-Leon** [comment]
Go to:

https://github.com/ROBOTIS-GIT/turtlebot3/issues/90
