### ISSUE TITLE
turtlebot3 segway example doesn't run well

### ISSUE THREAD

**Issue by ROBOTIS-Leon** [ROBOTIS-GIT/OpenCR#53]
1. Put a description that makes user:
1-1. change the dynamixel control mode into `pwm control mode`
1-2. put appropriate pose of the OpenCR board

2. Debug anything that are related with Filters.h
including : lowpassfilter() function

**Comment by routiful** [comment]
I noted that in E-Manual. Thank you for comment :)

**Comment by FerSalinas15** [comment]
Is there any manual about how to make it work? Step by step? I downloaded program as is but filter is not working, so I am currently using non filtered signal. Dynamixels move but segway is unstable. So far I have not been able to make it stable.
