### ISSUE TITLE
FreeRTOS

### ISSUE THREAD

**Issue by ufoncz** [ROBOTIS-GIT/OpenCR#55]
I have seen some FreeRTOS sources included the tree, but are they really used? I would like to port my realtime robot servo control code from Olimex STM32 board where I had FreeRTOS ported myself, to new OpenCR based on M7, so I am looking how it can be done easily. 
Can I use your FreeRTOS port from repo directly and bypass Arduino stuff, or is Arduino implementation internally using FreeRTOS and Arduino loop is just rtos task?
Sorry for maybe dumb question, but before I dive into many source files and spent useless time, I want to be sure what is the architecture behind OpenCR, I have not found any SW or SYS architectural document about OpenCR board, only some specs.
thanks, ufon

**Comment by chcbaram** [comment]
FreeRTOS is already ported to OpenCR. 
You just open the example to use the FreeRTOS below.

https://github.com/ROBOTIS-GIT/OpenCR/blob/master/arduino/opencr_arduino/opencr/libraries/OpenCR/examples/10.%20Etc/FreeRTOS/thread_led/thread_led.ino

FreeRTOS run only when you run example of FreeRTOS.

You can find the document of SW architecture of OpenCR below. 
https://www.slideshare.net/chcbaram/opencr-tutorialicra2017
