### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by EdXian** [ROBOTIS-GIT/OpenCR#60]
Hi team
I got the error as following . Though I reburn the bootloader ,the problem dosent fix.
Any idea?
![26803855_1290405727727028_1558075465_n](https://user-images.githubusercontent.com/28064159/34933494-07897266-fa12-11e7-9fef-0f6c26443806.png)

**Comment by chcbaram** [comment]
Hi EdXian. 

Did you try the recovery mode ? (https://github.com/ROBOTIS-GIT/OpenCR/wiki/Bootloader#firmware-recovery-mode)
It will be possible if the firmware was wrong so it didn't work so try the recovery mode and then upload the working firmware again.

**Comment by EdXian** [comment]
Hi @chcbaram ,
My problem has been solved .Thank you very much!!
