### ISSUE TITLE
How do I use "Wire.h" library ?

### ISSUE THREAD

**Issue by EdXian** [ROBOTIS-GIT/OpenCR#64]
Hi team , 
I want to include `Wire.h` library to my code . I find there are some definition in [I2Cdev.cpp](https://github.com/ROBOTIS-GIT/OpenCR/blob/master/arduino/opencr_arduino/opencr/libraries/I2Cdev/I2Cdev.h#L53-L81) and I try to change the definition as following:
```
#define I2CDEV_IMPLEMENTATION       I2CDEV_ARDUINO_WIRE
//#define I2CDEV_IMPLEMENTATION       I2CDEV_BUILTIN_FASTWIRE
```
and then include "Arduino.h" and "Wire.h" to my code:
```
#include "Arduino.h"
#include "Wire.h"
void setup() {
}

void loop() {
 
}
```
However , the compiler still cant find "Wire.h" .
Any Idea?
Thanks in advance .

**Comment by OpusK** [comment]
Hi, @EdXian 

Wire.h is not yet implemented.
Therefore, it can not be used even if the corresponding Define is used.
And the error is that there is no Wire.h in the board package. (Because it's not implemented yet)

I will discuss with the team about Wire.h support.

**Comment by EdXian** [comment]
Hi @OpusK ,
Thank you for your help!
I will use the library `i2Cdev` directly . Can you give me some example about I2Cdev?
Thanks again.

**Comment by OpusK** [comment]
There are no official examples using I2CDev. 
I will check to see if there is an internally implemented source.

**Comment by EdXian** [comment]
HI @OpusK ,
Ok , Thanks again!

**Comment by OpusK** [comment]
Hi, @EdXian 

It is not an example of OpenCR, but there is two examples using I2CDev to links below.

- [arduino_examples_oled_lcd / OpenCM9.04](https://github.com/ROBOTIS-GIT/OpenCM9.04/wiki/arduino_examples_oled_lcd)
- [arduino_examples_mpu6050_dmp / OpenCM9.04](https://github.com/ROBOTIS-GIT/OpenCM9.04/wiki/arduino_examples_mpu6050_dmp)

I think it is some useful reference to how I use the API of I2CDev.
