### ISSUE TITLE
UART

### ISSUE THREAD

**Issue by bberrevoets** [ROBOTIS-GIT/OpenCR#66]
Can we use the UART Connections on the board from Arduino?
And if the answer is yes, How do i do that?
Because i have a motorboard controller that is communicating over serial, i want that to connect to say UART1 on the board. And i want to create a class to read from the board, so the class must have aacces to  the UART, can you give me please an example?

Kind regards 
Bert Berrevoets.
![opencr](https://user-images.githubusercontent.com/4933105/35481656-f3884d80-0427-11e8-97a0-19c5ede73c34.png)

**Comment by OpusK** [comment]
Hello, @bberrevoets 

First, I apologize for any inconvenience you may have experienced.
We will rearrange the wiki page for the pinmap.

![](https://github.com/ROBOTIS-GIT/ROBOTIS-Documents/raw/master/wiki-images/OpenCR/specification_01.png?raw=true)

As shown in the illustration above, UART2 and UART4 are used, respectively.
And they are mapped to Serial2 and Serial4, respectively.

So, you can use the Serial2 class to use the UART you asked.

```cpp 
#define SERIAL Serial2

volatile int nCount=0;

void setup() {
  SERIAL.begin(115200);
}

void loop() {
  //print "Hello World!!" to PC though USB Virtual COM port
  SERIAL.println("Hello World!!");
  SERIAL.print("nCount : "); // display nCount variable and increase nCount.
  SERIAL.println(nCount++);
  
  delay(1000);
}
```
