### ISSUE TITLE
5VDC power only outputting 900mA

### ISSUE THREAD

**Issue by yycho0108** [ROBOTIS-GIT/OpenCR#75]
### Conditions

- Newly purchased (arrived **03/02/2018**) OpenCR Board from Turtlebot 3 Burger
- Powered from fully charged LiPo Battery that came with the kit
    - Also tried powering from SMPS, but did not help
- **Unable to adequately power SBC (ODROID XU4) from 5VDC@4A Output port**

### Main Issue

I don't know if this is the proper place to raise issues about the OpenCR Hardware.
I recently ordered Turtlebot 3 Burger from Dabit Industries, and fitted it with ODROID XU4 (as opposed to a Raspberry Pi 3).

Unfortunately, it got stuck in a loop of restarting, so I figured it must be an issue with the power supply.
When I checked the current on the 5VDC power output, it was only outputting 900mA ( according to the specifications, it should be able to supply 4A@5V; my battery was fully charged). This is a critical issue as it prevents the robot from operating untethered to power source for the SBC.

I had to order a new OpenCR board, as I didn't believe ROBOTIS would accept repairs/replacements for defects on a component from a part ordered from another distributor. While the shipment arrives, it would be great if you could double check on the fact that the board **could** supply 4A@5V at all. It was certainly unable to do so from the get-go.

**Comment by yycho0108** [comment]
Nothing else is plugged into the OpenCR except for the Dynamixels, as you mentioned, and the ODROID XU4 (5VDC for power, and USB connection for communication)

Can confirm that the ODROID XU4 runs fine on a separate power supply that provides 5V@4A.

**Comment by ROBOTIS-Will** [comment]
5V converter IC is XL4005 which can provide 5A at maximum so it should be able to supply enough power.  
If you need to get it repaired, you can get RMA for any defects on our product purchased from our distributors.  
Please visit our [repair center](http://en.robotis.com/model/page.php?co_id=repaircenter) :)

**Comment by yycho0108** [comment]
Update: it turned out to be a cable issue on my side. Thank you for all the help!
