### ISSUE TITLE
Support for dynamixel position control openCR TB3 

### ISSUE THREAD

**Issue by happyBear9** [ROBOTIS-GIT/OpenCR#81]
How could I control a third dynamixel XL430 motor (on turtlebot 3) in position control mode? I see that you defined the address for goal_position but not used it. Essentially a position control function in turtlebot_core 

 Thanks in advance

**Comment by ROBOTIS-Will** [comment]
For now, Dynamixel on TurtleBot3 are only controlled by velocity command.
If you wish to add additional Dynamixel that is controlled by position command, you need to modify the TurtleBot3 Core to receive position command and send it to additional XL430.
The good news is that the source code of OpenManipulator on TurtleBot3 waffle will be released within a couple weeks, so you can refer it as it will be very similar with what you want to do.
Thank you.

**Comment by happyBear9** [comment]
Thanks for the quick response. Ill modify the core and will post an update in this thread tomorrow.

**Comment by ROBOTIS-Will** [comment]
I think below thread would be useful to you.
[https://github.com/ROBOTIS-GIT/turtlebot3/issues/110](https://github.com/ROBOTIS-GIT/turtlebot3/issues/110)

**Comment by happyBear9** [comment]
I managed to get it to work! Just had to edit _turtlebot3_motor_driver.cpp_, _turtlebot3_motor_driver.h_, _turtlebot3_core.ino_ and _turtlebot3_core_config.h_

Thanks for quick responses! closing the topic

**Comment by hamidnrn** [comment]
can somebody tell me how I can control the position of Dynamixel X430-w210r?

**Comment by routiful** [comment]
You can use `DynamixelSDK` or `Dynamixel-Workbench` in OpenCR Example

http://emanual.robotis.com/docs/en/parts/controller/opencr10/#position

**Comment by hamidnrn** [comment]
I already did that I could drive it using MATLAB but I need a M.file helping me change the position and velocity suddenly ,by giving the specific degree to change

**Comment by routiful** [comment]
I think you can get a more information in SDK issue page.

https://github.com/ROBOTIS-GIT/DynamixelSDK/issues
