### ISSUE TITLE
angular velocity on /imu topic broken

### ISSUE THREAD

**Issue by ihadzic** [ROBOTIS-GIT/OpenCR#83]
I have recently upgraded the OpenCR firmware on my TB (I am now in the 1.1.2, before I was in 1.0.7). It looks like the units on /imu topic have been switched to radians (from raw ADC readings), but the numbers appear broken. I make the robot spin by exactly 1rad/s (verified correct by external means) and the imu/ topic reports 0.12 on z-axis angular velocity.

I believe the problem is that the calculations assume that the gyroscope range is +/-250 degrees (cf. the value of GYRO_FACTOR constant in turtlebot3_sensor.h), but the FS_SEL bits are still set to +/- 2000 range (see the register write to GYRO_CONFIG register in MPU9250.cpp)

**Comment by chcbaram** [comment]
@ihadzic 

You are right. GYRO_FACTOR and ACCEL_FACTOR are not correct value. Gyro is configured as +/-2000dps and Accel is configured as +/-2g so it should be like:
  ACCEL_FACTOR = 2.0/32768.0;        // 2g
  GYRO_FACTOR =  16.4;                   // 2000dps

It will be fixed next update.

**Comment by robotpilot** [comment]
@ihadzic, @chcbaram
This bug fix will be included in the next TurtleBot3 version upgrade.
I sincerely appreciate your feedback and will continue to provide better software in the future. :)
Thank you so much.

**Comment by robotpilot** [comment]
@OpusK, Does this software update include a workaround for this issue?

**Comment by ihadzic** [comment]
I have just updated to 1.1.13 and it looks like the gyroscope is still reporting incorrect reading. Looking at the source code, a comment has been added next to GYRO_FACTOR definition (and the math in the comment is correct), but the value has not been changed (it's still the old 0.000133)

```
#define GYRO_FACTOR                       0.000133  // pi / (131 * 180)      adc * 1/16.4 = deg/s => 1/16.4 deg/s -> 0.\
001064225157909 rad/s
```

**Comment by OpusK** [comment]
@robotpilot, @ihadzic, 

This issue has not been resolved in the 1.1.13 release.
I think it will be fixed in the next release.

**Comment by routiful** [comment]
Hi :) @ihadzic 

You can watch the code is replaced.

https://github.com/ROBOTIS-GIT/OpenCR/blob/develop/arduino/opencr_arduino/opencr/libraries/turtlebot3/include/turtlebot3/turtlebot3_sensor.h#L30

It will be updated soon.

Thanks

**Comment by routiful** [comment]
Hi again @ihadzic 

We update new firmware (version 1.2.0) :) Thank you to your contribution!
