### ISSUE TITLE
Opencr Board without USB - Usable ?

### ISSUE THREAD

**Issue by lucasilvassis** [ROBOTIS-GIT/OpenCR#89]
Hi guys, just bought a turtlebot 3 and noticed the USB port is detached from the board, some PCB paths were beyond recover by soldering. Can I still use the board with a Serial/USB adapter or other device? If so, witch connections should I make ?

**Comment by lucasilvassis** [comment]
Hi, @OpusK this is the closer i can get with focus on my phone, sorry if its no enough.

Two pahts were fully detached and one lost amost half of it for what i can tell. 

![image](https://user-images.githubusercontent.com/10927757/39611142-be88550e-4f2b-11e8-8e6d-3aaa2fb96abb.png)

Well, if there is no work around I will try to send it for repair, i guess it was damaged in factory/shipping and the USB port was just hanging.

**Comment by OpusK** [comment]
It seems to me that repair is difficult.

OK, please contact the [repair center](http://en.robotis.com/model/page.php?co_id=repaircenter) and check if repair is possible.

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
