### ISSUE TITLE
develop branch: inconsistent checking bumper method name...

### ISSUE THREAD

**Issue by KurtE** [ROBOTIS-GIT/OpenCR#97]
Currently the example waffle turtlebot waffle example program does not comple: 

```
DEBUG_SERIAL.print("Bumper : "); DEBUG_SERIAL.println(sensors.getPushedBumper());
```
It gives the Error:
```
'class Turtlebot3Sensor' has no member named 'getPushedBumper'
```

I believe that it was renamed in the last update to:

```
uint8_t Turtlebot3Sensor::checkPushBumper(void)
```

Not sure which one is correct?  Maybe half way inbetween? checkPushedBumper?

Kurt

**Comment by OpusK** [comment]
@KurtE 

We fixed this issue.
Thanks :)
